---
title: "Dirty Work"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(shiny)
library(ggforce)
library(readr)
library(dplyr)
```

```{r}
Premier_League_Dataset <- read_csv("Premier League Dataset.csv",
              col_types = 
                  cols(
                  .default = col_double(),
                  Date = col_character(),
                  HomeTeam = col_character(),
                  AwayTeam = col_character(),
                  FTR = col_character(),
                  HM1 = col_character(),
                  HM2 = col_character(),
                  HM3 = col_character(),
                  HM4 = col_character(),
                  HM5 = col_character(),
                  AM1 = col_character(),
                  AM2 = col_character(),
                  AM3 = col_character(),
                  AM4 = col_character(),
                  AM5 = col_character(),
                  HTFormPtsStr = col_character(),
                  ATFormPtsStr = col_character())
              )
```

```{r}
EPLStandings <- read_csv("EPLStandings.csv",
                      col_types = 
                          cols(
                          Team = col_character(),
                          `2000` = col_double(),
                          `2001` = col_double(),
                          `2002` = col_double(),
                          `2003` = col_double(),
                          `2004` = col_double(),
                          `2005` = col_double(),
                          `2006` = col_double(),
                          `2007` = col_double(),
                          `2008` = col_double(),
                          `2009` = col_double(),
                          `2010` = col_double(),
                          `2011` = col_double(),
                          `2012` = col_double(),
                          `2013` = col_double(),
                          `2014` = col_double(),
                          `2015` = col_double(),
                          `2016` = col_double())
                      )

```

```{r}

```
